### ISSUE TITLE
Short Videos

### ISSUE THREAD

**Issue by ShaiBer** [winglang/docsite#225]
In addition to the Wingly extracts, we'd like to create some more videos that are hard to do in that way.
We're not gonna invest a lot of resources in them, just pick low hanging fruit with high potential.

Some ideas:
- FAQ (some 20 questions and their answers. Film different people respond. Use materials in our documentation too)
- Short "Wing in 30 seconds" videos. Experiment with differnet styles and different messaging for different audiences. Use mainly VSC + Console screen recordings
- Short "Just wing it" videos. Show day to day struggles of cloud devs and then how we solve these pains with Wing

**Comment by ekeren** [comment]
closing, @ShaiBer will take this offline
