### ISSUE TITLE
Update Docs for snake_case -> camelCase

### ISSUE THREAD

**Issue by skorfmann** [winglang/docsite#416]
With this [PR](https://github.com/winglang/wing/pull/2468) being merged and released as v0.16, the docs should be updated accordingly. 

e.g. [add_consumer](https://github.com/winglang/docsite/blob/00604d7c31d81d73b9dd6bb37a820df0416740bf/versioned_docs/version-latest/01-welcome.md#L53) but there are more occasions.

Happy to do it, just wasn't sure if that's on someone's plate already.

**Comment by ShaiBer** [comment]
I have this PR waiting for approval for it: https://github.com/winglang/wing/pull/2484
(It's on the Wing repo since the docs are generated from there, except the blog)

**Comment by skorfmann** [comment]
Cool - I'll close this then :)
