### ISSUE TITLE
Cookie consent

### ISSUE THREAD

**Issue by eladb** [winglang/docsite#84]
We need to add a cookie consent since we are planning to install analytics on the website.

**Comment by boyney123** [comment]
Hey @eladb 

See this was raised a couple of years ago, still want/need this? Just checking before we migrate this over to monorepo issues.

**Comment by eladb** [comment]
I think we already have this; but I am not sure. @ainvoner is your man

**Comment by ainvoner** [comment]
We don't have it in our docs... only in our websites
